schema:
  enable: true
  path: /api/specs
metadata:
  sources: ['src/controllers/*']
  path: '.alliage-rest-api-metadata.json'
validation:
  requests:
    enable: true
  responses:
    enable: true
    errors:
      returnErrors: false
      statusCode: 500
development:
  disableMetadataGeneration: false