schema:
  enable: true
  path: /api/specs
metadata:
  sources: ['src/controllers/*']
  path: '.alliage-rest-api-metadata.json'
validation:
  requests:
    # Enable automatic validation of the requests
    enable: true
  response:
    # Enable automatic valivation of the responses
    enable: true
    errors:
      # Don't return an error if the response is invalid
      returnErrors: false
      statusCode: 500
development:
  # Enable automatic metadata generation when in development mode
  disableMetadataGeneration: false